<a href="https://colab.research.google.com/github/tremblay17/Machine-Learning-Projects/blob/main/StockClassifier-Keras-v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install yfinance
%pip install pandas_ta
%pip install optuna

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.model_selection import train_test_split
import keras as k
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.python.client import device_lib
from tensorflow.python.framework.ops import default_session
from keras.models import *
from keras.layers import *
from keras.optimizers import *
from keras.metrics import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris, load_digits
import yfinance as yf
import pandas_ta as ta
import optuna as o

In [ ]:
tf.test.gpu_device_name()
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11066356821046948268
xla_global_id: -1
]


In [ ]:
np.set_printoptions(precision=3, suppress=True)

startDate = "2022-12-06" #@param {type:"date"}
endDate = "2022-12-06" #@param {type: "date"}
stock = 'NVDA' #@param {type: "string"}
period = '10y' #@param ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y']
interval= '1d' #@param ['1m', '2m', '5m', '15m', '30m', '60m', '90m', '1h', '1d', '5d', '1wk', '1mo', '3mo']
toDate_historical = 'toDate' #@param ['toDate', 'historical']
length_days = 14 #@param {type:"slider", min:1, max:200, step:1}
macdFast = 12 #@param {type:"slider", min:1, max:200, step:1}
macdSlow = 26 #@param {type:"slider", min:1, max:200, step:1}
macdSignal = 9 #@param {type:"slider", min:1, max:200, step:1}
stochFastK = 14 #@param {type:"slider", min:1, max:200, step:1}
stochSlowK = 3 #@param {type:"slider", min:1, max:200, step:1}
stochD = 3 #@param {type:"slider", min:1, max:200, step:1}

if(toDate_historical == 'toDate'):
  data = yf.Ticker(stock).history(period=period, interval=interval)[
      ['Close', 'Open', 'High', 'Volume', 'Low']]
else:
  data = yf.Ticker(stock).history(start=startDate, end=endDate, interval=interval)[
      ['Close', 'Open', 'High', 'Volume', 'Low']]

data.ta.macd(close='close', fast=macdFast, slow=macdSlow, signal=macdSignal, append=True)
data.ta.adx(length=length_days, append=True)
data.ta.rsi(length=length_days, append=True)
data.ta.bbands(length=length_days, append=True)
data.ta.obv(append=True)
data.ta.stoch(high='High', low='Low', fast_k=stochFastK, slow_k=stochSlowK, slow_d=stochD, append=True)
data.ta.aroon(length=length_days, append=True)

print(data.info())

Class_Cat = []
Class_Int = []
for macd, macdh, macds, adx, dmp, dmn, rsi, bbl, bbm, bbu, bbb, bbp, obv, stochk, stochd, aroond, aroonu, aroonosc in data.iloc[:, 5:].values:
  if ((macd == 'NaN') or (macdh == 'NaN') or (macds == 'NaN') or (adx == 'NaN') or (dmp == 'NaN') or (dmn == 'NaN') or (rsi == 'NaN')):
    Class_Cat.append('Hold')
    Class_Int.append(1)
  elif (((macd >= macds) and (macdh > 0) and ((adx >= 25) and (dmp > dmn))) or (rsi <= 30)):
    Class_Cat.append('Buy')
    Class_Int.append(0)
  elif (((macd <= macds) and (macdh < 0) and ((adx >= 25) and (dmn > dmp))) or (rsi >= 70)):
    Class_Cat.append('Sell')
    Class_Int.append(2)
  else:
    Class_Cat.append('Hold')
    Class_Int.append(1)

data['Class_Int'] = Class_Int
data['Class_Cat'] = Class_Cat
data = data.iloc[34:, :]
data.head(60)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2012-12-10 00:00:00-05:00 to 2022-12-08 00:00:00-05:00
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Close          2518 non-null   float64
 1   Open           2518 non-null   float64
 2   High           2518 non-null   float64
 3   Volume         2518 non-null   int64  
 4   Low            2518 non-null   float64
 5   MACD_12_26_9   2493 non-null   float64
 6   MACDh_12_26_9  2485 non-null   float64
 7   MACDs_12_26_9  2485 non-null   float64
 8   ADX_14         2491 non-null   float64
 9   DMP_14         2504 non-null   float64
 10  DMN_14         2504 non-null   float64
 11  RSI_14         2504 non-null   float64
 12  BBL_14_2.0     2505 non-null   float64
 13  BBM_14_2.0     2505 non-null   float64
 14  BBU_14_2.0     2505 non-null   float64
 15  BBB_14_2.0     2505 non-null   float64
 16  BBP_14_2.0     2505 non-null   float64
 17  OBV 

Close      Open      High    Volume       Low  \
Date                                                                          
2013-01-30 00:00:00-05:00  2.844914  2.851841  2.891098  28759200  2.835677   
2013-01-31 00:00:00-05:00  2.831058  2.844913  2.877242  47054400  2.812585   
2013-02-01 00:00:00-05:00  2.856460  2.854151  2.865697  28881600  2.831059   
2013-02-04 00:00:00-05:00  2.807967  2.840296  2.898025  51174400  2.805658   
2013-02-05 00:00:00-05:00  2.872623  2.821822  2.888788  36729600  2.812585   
2013-02-06 00:00:00-05:00  2.849532  2.803349  2.872624  53068800  2.787184   
2013-02-07 00:00:00-05:00  2.837986  2.840295  2.863387  44000000  2.810276   
2013-02-08 00:00:00-05:00  2.856460  2.856460  2.879552  30723200  2.837986   
2013-02-11 00:00:00-05:00  2.888788  2.879551  2.918807  40830800  2.851841   
2013-02-12 00:00:00-05:00  2.870315  2.863387  2.902643  27780400  2.858769   
2013-02-13 00:00:00-05:00  2.856460  2.872624  2.925735  85639600  2.847223   
2013-02-14 00:00:00-05:00  2.939590  2.817203  2.941899  88209600  2.782565   
2013-02-15 00:00:00-05:00  2.939590  2.932662  2.953445  73386000  2.874932   
2013-02-19 00:00:00-05:00  2.900334  2.941899  2.944209  43355200  2.881860   
2013-02-20 00:00:00-05:00  2.858769  2.909571  2.955755  71301200  2.849532   
2013-02-21 00:00:00-05:00  2.837986  2.854150  2.886479  58040800  2.831059   
2013-02-22 00:00:00-05:00  2.891097  2.856459  2.893406  37014800  2.840295   
2013-02-25 00:00:00-05:00  2.840295  2.898025  2.921116  64444400  2.835677   
2013-02-26 00:00:00-05:00  2.873983  2.846103  2.890247  48750400  2.836810   
2013-02-27 00:00:00-05:00  2.927421  2.873983  2.948331  47698000  2.867013   
2013-02-28 00:00:00-05:00  2.941361  2.918127  2.985504  59139200  2.906511   
2013-03-01 00:00:00-05:00  2.952978  2.920451  2.962271  38939600  2.894894   
2013-03-04 00:00:00-05:00  2.941361  2.932067  2.969241  35368000  2.908834   
2013-03-05 00:00:00-05:00  2.973888  2.957625  2.978535  36616800  2.943685   
2013-03-06 00:00:00-05:00  2.971564  2.992474  3.020355  34292800  2.957624   
2013-03-07 00:00:00-05:00  2.964594  2.987828  3.018031  31482400  2.948331   
2013-03-08 00:00:00-05:00  2.978535  2.971565  2.992475  24646400  2.957625   
2013-03-11 00:00:00-04:00  2.950654  2.948331  2.962271  29974800  2.925097   
2013-03-12 00:00:00-04:00  2.959948  2.946008  2.969241  31085600  2.918127   
2013-03-13 00:00:00-04:00  2.959948  2.959948  3.011061  48584000  2.932067   
2013-03-14 00:00:00-04:00  2.962270  2.978534  2.987827  38330400  2.943684   
2013-03-15 00:00:00-04:00  2.936714  2.962271  2.962271  35577600  2.925097   
2013-03-18 00:00:00-04:00  2.915804  2.918128  2.943685  29831200  2.894894   
2013-03-19 00:00:00-04:00  2.897217  2.918127  2.932067  35548000  2.876307   
2013-03-20 00:00:00-04:00  2.932068  2.925098  2.941361  34058800  2.899541   
2013-03-21 00:00:00-04:00  2.885601  2.915804  2.920451  33903200  2.880954   
2013-03-22 00:00:00-04:00  2.899540  2.894894  2.911157  23247600  2.883277   
2013-03-25 00:00:00-04:00  2.883276  2.915803  2.918127  36207600  2.862366   
2013-03-26 00:00:00-04:00  2.904187  2.890247  2.906511  23254000  2.878630   
2013-03-27 00:00:00-04:00  2.939038  2.892571  2.955302  25494400  2.885601   
2013-03-28 00:00:00-04:00  2.980857  2.932067  2.983180  34927600  2.911156   
2013-04-01 00:00:00-04:00  2.883276  2.973887  2.973887  44282800  2.862366   
2013-04-02 00:00:00-04:00  2.853074  2.885601  2.892571  37152400  2.834487   
2013-04-03 00:00:00-04:00  2.818224  2.848427  2.864691  35315600  2.797314   
2013-04-04 00:00:00-04:00  2.846104  2.808930  2.855397  29467600  2.799637   
2013-04-05 00:00:00-04:00  2.894894  2.804283  2.894894  55135200  2.797313   
2013-04-08 00:00:00-04:00  2.887924  2.897218  2.897218  32666000  2.834487   
2013-04-09 00:00:00-04:00  2.934391  2.890247  2.955301  38058400  2.869337   
2013-04-10 00:00:00-04:00  2.980857  2.936713  2.985504  38468800  2.929743   
2

In [ ]:
data_inputs = data.iloc[:, 0:23].values
data_class = data.iloc[:, 23:24].values
print(data_class)


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]


In [ ]:
# Classes 'Buy(1)', 'Hold(0)', or 'Sell(2)'
np.asarray(data_inputs).astype('float64')
np.asarray(data_class).astype('float64')


array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [ ]:

sc = MinMaxScaler(feature_range=(0, 1))
x_train, x_test, y_train, y_test = train_test_split(
    data_inputs, data_class, train_size=0.75)


In [ ]:
# Normalization

sc.fit(x_train)
sc.transform(x_train)
sc.transform(x_test)

x_train.shape


(1863, 23)

In [ ]:

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
x_train.shape


(1863, 23, 1)

In [ ]:
 #Currently generates the highest accuracy
#{'layer1': 75, 'activation1': 'tanh',
#'layer2': 85, 'activation2': 'softsign',
#'layer3': 73, 'activation3': 'softsign',
#'layer4': 29, 'activation4': 'relu',
#'learning rate': 0.006548463552532551}

layerSize_1 = 75 #@param {type:"slider", min:1, max:200, step:1}
layerSize_2 = 85 #@param {type:"slider", min:1, max:200, step:1}
layerSize_3 = 73 #@param {type:"slider", min:1, max:200, step:1}
layerSize_4 = 29 #@param {type:"slider", min:1, max:200, step:1}

seqModel = Sequential(
    [
        LSTM(units=layerSize_1, return_sequences=True, activation='tanh',
             input_shape=(x_train.shape[1], 1)),

        LSTM(units=layerSize_2, return_sequences=True, activation='softsign'),

        LSTM(units=layerSize_3, return_sequences=True, activation='softsign'),

        LSTM(units=layerSize_4, activation='relu'),

        Dense(units=3, activation='sigmoid')
    ]
)
#Adding a 5th layer led to Diminishing Returns


In [ ]:
#@title Default title text
from keras.losses import *

lossFunc = SparseCategoricalCrossentropy() #@param ["SparseCategoricalCrossentropy()", "Poisson()", "KLDivergence()"] {type:"raw"}
batchSize = 64  #@param {type:"slider", min:1, max:200, step:1}
epochs = 75  #@param {type:"slider", min:1, max:200, step:1}
optimizer = Adam(learning_rate=0.006548463552532551) #@param ["Adam(learning_rate=0.006548463552532551)", "Adadelta()", "Adamax()", "Nadam()", 'SGD()'] {type:"raw"}
metrics = [SparseCategoricalAccuracy(), MeanAbsoluteError(), MeanSquaredError(), CategoricalHinge(), Poisson(), KLDivergence()]
seqModel.compile(optimizer=optimizer, loss=lossFunc, metrics=metrics)


In [ ]:
seqModel.fit(x_train,
             y_train,
             validation_data=(x_test, y_test),
             epochs=epochs, batch_size=batchSize, validation_batch_size=batchSize)

Epoch 1/75
30/30 [==============================] - 20s 325ms/step - loss: 0.8826 - sparse_categorical_accuracy: 0.6479 - mean_absolute_error: 0.5656 - mean_squared_error: 0.4483 - categorical_hinge: 0.3625 - poisson: 1.0983 - kl_divergence: 1.2894 - val_loss: 0.8330 - val_sparse_categorical_accuracy: 0.6844 - val_mean_absolute_error: 0.5910 - val_mean_squared_error: 0.4751 - val_categorical_hinge: 0.3314 - val_poisson: 1.1322 - val_kl_divergence: 1.4951
Epoch 2/75
30/30 [==============================] - 4s 121ms/step - loss: 0.7554 - sparse_categorical_accuracy: 0.6758 - mean_absolute_error: 0.5779 - mean_squared_error: 0.4846 - categorical_hinge: 0.3596 - poisson: 1.1303 - kl_divergence: 1.3904 - val_loss: 0.7861 - val_sparse_categorical_accuracy: 0.5942 - val_mean_absolute_error: 0.5495 - val_mean_squared_error: 0.4740 - val_categorical_hinge: 0.3540 - val_poisson: 1.1496 - val_kl_divergence: 1.3680
Epoch 3/75
30/30 [==============================] - 3s 109ms/step - loss: 0.6548 - 

In [ ]:
print(seqModel.evaluate(x_train, y_train))
seqModel.evaluate(x_test, y_test)

59/59 [==============================] - 1s 21ms/step - loss: 0.1501 - sparse_categorical_accuracy: 0.9431 - mean_absolute_error: 0.6668 - mean_squared_error: 0.7219 - categorical_hinge: 0.4016 - poisson: 2.7172 - kl_divergence: 6.1180
[0.15014289319515228, 0.9431025385856628, 0.6668065190315247, 0.7218831777572632, 0.4015952944755554, 2.7171807289123535, 6.117966651916504]
20/20 [==============================] - 0s 21ms/step - loss: 0.4677 - sparse_categorical_accuracy: 0.8937 - mean_absolute_error: 0.6715 - mean_squared_error: 0.7299 - categorical_hinge: 0.3774 - poisson: 2.7567 - kl_divergence: 6.3225


[0.4676613509654999,
 0.8937197923660278,
 0.6714918613433838,
 0.7299188375473022,
 0.37735414505004883,
 2.756727457046509,
 6.322474479675293]

In [ ]:
print(x_test)
pred = seqModel.predict(x_train)

[[[  3.722]
  [  3.725]
  [  3.753]
  ...
  [ 28.571]
  [ 92.857]
  [ 64.286]]

 [[301.698]
  [311.209]
  [312.758]
  ...
  [ 71.429]
  [  7.143]
  [-64.286]]

 [[  7.247]
  [  7.242]
  [  7.298]
  ...
  [100.   ]
  [ 50.   ]
  [-50.   ]]

 ...

 [[121.389]
  [124.593]
  [126.259]
  ...
  [ 78.571]
  [ 57.143]
  [-21.429]]

 [[ 23.212]
  [ 23.276]
  [ 23.444]
  ...
  [  0.   ]
  [ 92.857]
  [ 92.857]]

 [[134.576]
  [137.234]
  [137.714]
  ...
  [ 85.714]
  [  0.   ]
  [-85.714]]]
59/59 [==============================] - 2s 20ms/step


In [ ]:
np.set_printoptions(precision=3, suppress=True)

stock = 'GOOGL'

if(toDate_historical == 'toDate'):
  data = yf.Ticker(stock).history(period=period, interval=interval)[
      ['Close', 'Open', 'High', 'Volume', 'Low']]
else:
  data = yf.Ticker(stock).history(start=startDate, end=endDate, interval=interval)[
      ['Close', 'Open', 'High', 'Volume', 'Low']]

data.ta.macd(close='close', fast=macdFast, slow=macdSlow, signal=macdSignal, append=True)
data.ta.adx(length=length_days, append=True)
data.ta.rsi(length=length_days, append=True)
data.ta.bbands(length=length_days, append=True)
data.ta.obv(append=True)
data.ta.stoch(high='High', low='Low', fast_k=stochFastK, slow_k=stochSlowK, slow_d=stochD, append=True)
data.ta.aroon(length=length_days, append=True)

print(data.info())

Class_Cat = []
Class_Int = []
for macd, macdh, macds, adx, dmp, dmn, rsi, bbl, bbm, bbu, bbb, bbp, obv, stochk, stochd, aroond, aroonu, aroonosc in data.iloc[:, 5:].values:
  if ((macd == 'NaN') or (macdh == 'NaN') or (macds == 'NaN') or (adx == 'NaN') or (dmp == 'NaN') or (dmn == 'NaN') or (rsi == 'NaN')):
    Class_Cat.append('Hold')
    Class_Int.append(1)
  elif (((macd >= macds) and (macdh > 0) and ((adx >= 25) and (dmp > dmn))) or (rsi <= 30)):
    Class_Cat.append('Buy')
    Class_Int.append(0)
  elif (((macd <= macds) and (macdh < 0) and ((adx >= 25) and (dmn > dmp))) or (rsi >= 70)):
    Class_Cat.append('Sell')
    Class_Int.append(2)
  else:
    Class_Cat.append('Hold')
    Class_Int.append(1)

data['Class_Int'] = Class_Int
data['Class_Cat'] = Class_Cat
data = data.iloc[34:, :]

data_inputs = data.iloc[:, 0:23].values
data_class = data.iloc[:, 23:24].values
print(data_class)

# Classes 'Buy(1)', 'Hold(0)', or 'Sell(2)'
np.asarray(data_inputs).astype('float64')
np.asarray(data_class).astype('float64')
sc = MinMaxScaler(feature_range=(0, 1))
x_train, x_test, y_train, y_test = train_test_split(
    data_inputs, data_class, train_size=0.5)
# Normalization
sc.fit(x_train)
sc.transform(x_test)

x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))


print(data.head(5))
data.tail(5)


<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2012-12-10 00:00:00-05:00 to 2022-12-08 00:00:00-05:00
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Close          2518 non-null   float64
 1   Open           2518 non-null   float64
 2   High           2518 non-null   float64
 3   Volume         2518 non-null   int64  
 4   Low            2518 non-null   float64
 5   MACD_12_26_9   2493 non-null   float64
 6   MACDh_12_26_9  2485 non-null   float64
 7   MACDs_12_26_9  2485 non-null   float64
 8   ADX_14         2491 non-null   float64
 9   DMP_14         2504 non-null   float64
 10  DMN_14         2504 non-null   float64
 11  RSI_14         2504 non-null   float64
 12  BBL_14_2.0     2505 non-null   float64
 13  BBM_14_2.0     2505 non-null   float64
 14  BBU_14_2.0     2505 non-null   float64
 15  BBB_14_2.0     2505 non-null   float64
 16  BBP_14_2.0     2505 non-null   float64
 17  OBV 

Close       Open        High    Volume  \
Date                                                                     
2022-12-02 00:00:00-05:00  100.440002  99.050003  100.769997  21469400   
2022-12-05 00:00:00-05:00   99.480003  99.400002  101.379997  24405100   
2022-12-06 00:00:00-05:00   96.980003  99.300003   99.779999  24910700   
2022-12-07 00:00:00-05:00   94.940002  96.410004   96.879997  31045400   
2022-12-08 00:00:00-05:00   93.709999  95.379997   95.580002  32185900   

                                 Low  MACD_12_26_9  MACDh_12_26_9  \
Date                                                                
2022-12-02 00:00:00-05:00  98.900002      0.960859       0.760079   
2022-12-05 00:00:00-05:00  99.000000      1.013695       0.650332   
2022-12-06 00:00:00-05:00  96.419998      0.844108       0.384597   
2022-12-07 00:00:00-05:00  94.720001      0.538887       0.063500   
2022-12-08 00:00:00-05:00  93.449997      0.195492      -0.223916   

                           MACDs_12_26_9     ADX_14     DMP_14  ...  \
Date                                                            ...   
2022-12-02 00:00:00-05:00       0.200779  15.848050  30.030002  ...   
2022-12-05 00:00:00-05:00       0.363363  15.398250  29.779237  ...   
2022-12-06 00:00:00-05:00       0.459512  14.469444  27.404516  ...   
2022-12-07 00:00:00-05:00       0.475387  14.107694  25.907982  ...   
2022-12-08 00:00:00-05:00       0.419408  14.125266  24.547394  ...   

                           BBB_14_2.0  BBP_14_2.0           OBV  \
Date                                                              
2022-12-02 00:00:00-05:00    7.664025    0.834525  5.136061e+09   
2022-12-05 00:00:00-05:00    7.359703    0.677209  5.111656e+09   
2022-12-06 00:00:00-05:00    7.469703    0.347832  5.086745e+09   
2022-12-07 00:00:00-05:00    8.125273    0.138175  5.055700e+09   
2022-12-08 00:00:00-05:00    9.193993    0.078966  5.023514e+09   

                           STOCHk_14_3_3  STOCHd_14_3_3   AROOND_14  \
Date                                                                  
2022-12-02 00:00:00-05:00      87.423508      81.921898    0.000000   
2022-12-05 00:00:00-05:00      76.340106      81.904788   42.857143   
2022-12-06 00:00:00-05:00      59.959372      74.574329   35.714286   
2022-12-07 00:00:00-05:00      37.601640      57.967039   28.571429   
2022-12-08 00:00:00-05:00      16.513316      38.024776  100.000000   

                           AROONU_14  AROONOSC_14  Class_Int  Class_Cat  
Date                                                                     
2022-12-02 00:00:00-05:00  92.857143    92.857143          1       Hold  
2022-12-05 00:00:00-05:00  85.714286    42.857143          1       Hold  
2022-12-06 00:00:00-05:00  78.571429    42.857143          1       Hold  
2022-12-07 00:00:00-05:00  71.428571    42.857143          1       Hold  
2022-12-08 00:00:00-05:00  64.285714   -35.714286          1       Hold  

[5 rows x 25 columns]

In [ ]:
print(seqModel.predict(x_test))


39/39 [==============================] - 1s 21ms/step
[[0.004 0.969 0.949]
 [0.001 1.    0.065]
 [0.004 0.489 0.991]
 ...
 [0.001 1.    0.278]
 [0.02  0.999 0.096]
 [0.    1.    0.186]]
